import type { BrewingStepKind, Ingredient, MenuItem } from '../types/entities'

export const INGREDIENTS: Ingredient[] = [
  { id: 'ing.coffee_bean', name: 'Cà phê hạt', unit: 'g', pricePerUnit: 200, initialStock: 2000, icon: '🫘' },
  { id: 'ing.milk', name: 'Sữa tươi', unit: 'ml', pricePerUnit: 30, initialStock: 5000, icon: '🥛' },
  { id: 'ing.sugar', name: 'Đường', unit: 'g', pricePerUnit: 15, initialStock: 2000, icon: '🍯' },
  { id: 'ing.tea_leaf', name: 'Lá trà', unit: 'g', pricePerUnit: 150, initialStock: 1000, icon: '🍃' },
  { id: 'ing.flour', name: 'Bột mì', unit: 'g', pricePerUnit: 25, initialStock: 3000, icon: '🌾' },
  { id: 'ing.egg', name: 'Trứng', unit: 'piece', pricePerUnit: 4000, initialStock: 50, icon: '🥚' },
  { id: 'ing.butter', name: 'Bơ', unit: 'g', pricePerUnit: 200, initialStock: 1000, icon: '🧈' },
  { id: 'ing.chocolate', name: 'Sôcôla', unit: 'g', pricePerUnit: 500, initialStock: 500, icon: '🍫' },
  { id: 'ing.ice', name: 'Đá', unit: 'g', pricePerUnit: 5, initialStock: 5000, icon: '🧊' },
  { id: 'ing.condensed_milk', name: 'Sữa đặc', unit: 'ml', pricePerUnit: 50, initialStock: 2000, icon: '🥫' },
]

type SeedItem = Omit<MenuItem, 'popularityScore' | 'salesCount'>

const RECIPES = {
  espresso: ['grind', 'tamp', 'extract'] as BrewingStepKind[],
  americano: ['grind', 'tamp', 'extract', 'pour_milk'] as BrewingStepKind[],
  cappuccino: ['grind', 'tamp', 'extract', 'steam_milk', 'pour_milk'] as BrewingStepKind[],
  latte: ['grind', 'tamp', 'extract', 'steam_milk', 'pour_milk'] as BrewingStepKind[],
  mocha: ['grind', 'tamp', 'extract', 'add_chocolate', 'steam_milk', 'pour_milk'] as BrewingStepKind[],
  vietnamese: ['grind', 'tamp', 'extract', 'add_chocolate'] as BrewingStepKind[],
  iced_coffee: ['grind', 'tamp', 'extract', 'add_ice', 'pour_milk'] as BrewingStepKind[],
  green_tea: ['add_tea_bag', 'add_sugar', 'whisk'] as BrewingStepKind[],
  milk_tea: ['add_tea_bag', 'pour_milk', 'add_sugar', 'whisk'] as BrewingStepKind[],
  matcha_latte: ['whisk', 'steam_milk', 'pour_milk', 'sprinkle'] as BrewingStepKind[],
  croissant: ['sprinkle'] as BrewingStepKind[],
  tiramisu: ['sprinkle'] as BrewingStepKind[],
  chocolate_cake: ['sprinkle'] as BrewingStepKind[],
}

export const STARTER_MENU: SeedItem[] = [
  {
    id: 'menu.espresso',
    name: 'Espresso',
    category: 'coffee',
    price: 25_000,
    baseCost: 5_000,
    prepTimeSeconds: 45,
    isAvailable: true,
    unlocked: true,
    ingredients: [{ ingredientId: 'ing.coffee_bean', amount: 18 }],
    icon: '☕',
    brewingSteps: RECIPES.espresso,
  },
  {
    id: 'menu.americano',
    name: 'Americano',
    category: 'coffee',
    price: 30_000,
    baseCost: 5_500,
    prepTimeSeconds: 50,
    isAvailable: true,
    unlocked: true,
    ingredients: [{ ingredientId: 'ing.coffee_bean', amount: 20 }],
    icon: '☕',
    brewingSteps: RECIPES.americano,
  },
  {
    id: 'menu.cappuccino',
    name: 'Cappuccino',
    category: 'coffee',
    price: 45_000,
    baseCost: 9_000,
    prepTimeSeconds: 70,
    isAvailable: true,
    unlocked: true,
    ingredients: [
      { ingredientId: 'ing.coffee_bean', amount: 18 },
      { ingredientId: 'ing.milk', amount: 150 },
    ],
    icon: '☕',
    brewingSteps: RECIPES.cappuccino,
  },
  {
    id: 'menu.latte',
    name: 'Latte',
    category: 'coffee',
    price: 50_000,
    baseCost: 10_000,
    prepTimeSeconds: 75,
    isAvailable: true,
    unlocked: true,
    ingredients: [
      { ingredientId: 'ing.coffee_bean', amount: 18 },
      { ingredientId: 'ing.milk', amount: 200 },
    ],
    icon: '☕',
    brewingSteps: RECIPES.latte,
  },
  {
    id: 'menu.mocha',
    name: 'Mocha',
    category: 'coffee',
    price: 55_000,
    baseCost: 13_000,
    prepTimeSeconds: 80,
    isAvailable: false,
    unlocked: false,
    ingredients: [
      { ingredientId: 'ing.coffee_bean', amount: 18 },
      { ingredientId: 'ing.milk', amount: 180 },
      { ingredientId: 'ing.chocolate', amount: 20 },
    ],
    icon: '☕',
    brewingSteps: RECIPES.mocha,
  },
  {
    id: 'menu.vietnamese',
    name: 'Cà phê sữa đá',
    category: 'coffee',
    price: 35_000,
    baseCost: 7_500,
    prepTimeSeconds: 60,
    isAvailable: true,
    unlocked: true,
    ingredients: [
      { ingredientId: 'ing.coffee_bean', amount: 20 },
      { ingredientId: 'ing.condensed_milk', amount: 30 },
      { ingredientId: 'ing.ice', amount: 100 },
    ],
    icon: '🧋',
    brewingSteps: RECIPES.vietnamese,
  },
  {
    id: 'menu.iced_coffee',
    name: 'Cà phê đá',
    category: 'coffee',
    price: 28_000,
    baseCost: 6_000,
    prepTimeSeconds: 55,
    isAvailable: true,
    unlocked: true,
    ingredients: [
      { ingredientId: 'ing.coffee_bean', amount: 20 },
      { ingredientId: 'ing.ice', amount: 100 },
    ],
    icon: '🧊',
    brewingSteps: RECIPES.iced_coffee,
  },
  {
    id: 'menu.green_tea',
    name: 'Trà xanh',
    category: 'tea',
    price: 35_000,
    baseCost: 6_000,
    prepTimeSeconds: 60,
    isAvailable: true,
    unlocked: true,
    ingredients: [
      { ingredientId: 'ing.tea_leaf', amount: 5 },
      { ingredientId: 'ing.sugar', amount: 10 },
    ],
    icon: '🍵',
    brewingSteps: RECIPES.green_tea,
  },
  {
    id: 'menu.milk_tea',
    name: 'Trà sữa',
    category: 'tea',
    price: 40_000,
    baseCost: 8_000,
    prepTimeSeconds: 65,
    isAvailable: false,
    unlocked: false,
    ingredients: [
      { ingredientId: 'ing.tea_leaf', amount: 5 },
      { ingredientId: 'ing.milk', amount: 200 },
      { ingredientId: 'ing.sugar', amount: 15 },
    ],
    icon: '🧋',
    brewingSteps: RECIPES.milk_tea,
  },
  {
    id: 'menu.matcha_latte',
    name: 'Matcha Latte',
    category: 'tea',
    price: 55_000,
    baseCost: 14_000,
    prepTimeSeconds: 75,
    isAvailable: false,
    unlocked: false,
    ingredients: [
      { ingredientId: 'ing.tea_leaf', amount: 8 },
      { ingredientId: 'ing.milk', amount: 200 },
    ],
    icon: '🍵',
    brewingSteps: RECIPES.matcha_latte,
  },
  {
    id: 'menu.croissant',
    name: 'Bánh sừng bò',
    category: 'food',
    price: 35_000,
    baseCost: 9_000,
    prepTimeSeconds: 30,
    isAvailable: true,
    unlocked: true,
    ingredients: [
      { ingredientId: 'ing.flour', amount: 60 },
      { ingredientId: 'ing.butter', amount: 30 },
      { ingredientId: 'ing.egg', amount: 1 },
    ],
    icon: '🥐',
    brewingSteps: RECIPES.croissant,
  },
  {
    id: 'menu.tiramisu',
    name: 'Tiramisu',
    category: 'dessert',
    price: 65_000,
    baseCost: 16_000,
    prepTimeSeconds: 35,
    isAvailable: false,
    unlocked: false,
    ingredients: [
      { ingredientId: 'ing.flour', amount: 50 },
      { ingredientId: 'ing.egg', amount: 2 },
      { ingredientId: 'ing.chocolate', amount: 20 },
    ],
    icon: '🍰',
    brewingSteps: RECIPES.tiramisu,
  },
  {
    id: 'menu.chocolate_cake',
    name: 'Bánh sôcôla',
    category: 'dessert',
    price: 60_000,
    baseCost: 18_000,
    prepTimeSeconds: 40,
    isAvailable: false,
    unlocked: false,
    ingredients: [
      { ingredientId: 'ing.flour', amount: 80 },
      { ingredientId: 'ing.chocolate', amount: 40 },
      { ingredientId: 'ing.egg', amount: 2 },
      { ingredientId: 'ing.butter', amount: 40 },
    ],
    icon: '🎂',
    brewingSteps: RECIPES.chocolate_cake,
  },
]
